### ISSUE TITLE
release

### ISSUE THREAD

**Issue by till** [Behat/CommonContexts#57]
Can you guys release a 1.2.1 or so?

Or what's the plan? :)

**Comment by afterdesign** [comment]
:+1:

**Comment by MacDada** [comment]
[Waiting for the release](https://github.com/Behat/CommonContexts/issues/51#issuecomment-152290987) :+1:

**Comment by kslimani** [comment]
What about also another tag for PHPUnit 5.0+ require support ? (current stable release).

**Comment by Mischosch** [comment]
*ping*

**Comment by bocharsky-bw** [comment]
👍

**Comment by dragu** [comment]
RIP?

**Comment by localheinz** [comment]
@dragu 

https://github.com/Behat/CommonContexts#this-project-is-abandoned
