### ISSUE TITLE
Behat 3 integration

### ISSUE THREAD

**Issue by tis-dm-webfactory** [Behat/CommonContexts#58]
How do I include this in behat3?

**Comment by stof** [comment]
This package has not yet been updated to Behat 3. Half of the contexts available here should actually not be implemented as contexts but as extensions (which were not yet available in Behat at the time this repo was created).
for the WebApiContext, there is an extension created for Behat 3 to expose the same features.

**Comment by tis-dm-webfactory** [comment]
ok thank you for the information!
